version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app/src
    command: ["sh", "-c", "PYTHONPATH=src uvicorn app.main:app --host 0.0.0.0 --port 8000"]
